# Generated by Django 4.0.6 on 2022-08-08 10:23

import authe.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.PositiveBigIntegerField(validators=[authe.validators.phone10]),
        ),
    ]
