# Generated by Django 3.2.14 on 2022-07-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=130)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='multiple.product')),
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiple.customer')),
                ('address', models.CharField(max_length=20)),
                ('shopaddress', models.CharField(max_length=20)),
                ('lino', models.CharField(max_length=20)),
            ],
            bases=('multiple.customer', 'multiple.product'),
        ),
    ]
