# Generated by Django 4.0.6 on 2022-07-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemmodel',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.itemmodel')),
            ],
        ),
    ]
