# Generated by Django 3.2.14 on 2022-07-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=130)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('details_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hier.details')),
                ('proc', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=30)),
                ('battery', models.CharField(max_length=30)),
            ],
            bases=('hier.details',),
        ),
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('details_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hier.details')),
                ('proc', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('camera', models.CharField(max_length=30)),
                ('battery', models.CharField(max_length=30)),
            ],
            bases=('hier.details',),
        ),
    ]
