# Generated by Django 3.2.14 on 2022-07-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cricketmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('matches', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('avg', models.FloatField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
