# Generated by Django 3.2.14 on 2022-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmodel',
            name='gender',
            field=models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
