# Generated by Django 3.2.14 on 2022-07-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('nofcust', models.IntegerField()),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vbank',
            fields=[
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='single.bank')),
                ('ifsc', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
            bases=('single.bank',),
        ),
    ]
